const router = require('express').Router()
const conekta = require('conekta')

conekta.api_key = process.env.CONEKTA_KEY
conekta.api_version = '2.0.0';
conekta.locale = 'es'

router.post('/conekta', (req, res, next)=>{
  
  //We need the specific course asigned to the user
  //we need the frontend token generated by conekta
  const {conektaTokenId, course} = req.body
  const {user} = req.user

  conekta.Order.create(
    {
      currency: "MXN",
      customer_info: {
        name: user.name,
        phone: user.phone,
        email: user.email
      },
      line_items: [
        {
          name: course.name,
          unit_price: course.price,
          quantity: 1
        }
      ],      
      charges: [
        {
          payment_method: {
            type: "card",
            token_id: conektaTokenId
          }
        }
      ]
    },
    function(err, order) {
      if (err) return res.send(err);
      console.log(order.toObject());
      return res.send(order.toObject());
    }
  );
})


module.exports = router




