const router = require('express').Router()
const conekta = require('conekta')

conekta.api_key = process.env.CONEKTA_KEY
conekta.api_version = '2.0.0';
conekta.locale = 'es'

router.post('/conekta', (req, res, next)=>{
  
  //We need the specific course asigned to the user
  //we need the frontend token generated by conekta
  const {conektaTokenId} = req.body

  //creating a customer
  // customer = conekta.Customer.create({
  //   'name': 'Oswaldito',
  //   'email': 'os@fixter.org',
  //   'phone': '+52 7711732959',
    
  //   'payment_sources': [{
  //     'type': 'card',
  //     'token_id': 'tok_test_visa_4242'
  //     //'token_id': request.data['token']['id']
  //   }]
  // })

  const course = {
    name:'Oswaldinho Course',
    price:500
  }
  conekta.Order.create(
    {
      currency: "MXN",
      customer_info: {
        name: 'Héctor Bliss',//process.env.CONEKTA_NAME,
        phone: '+527712412825',//process.env.CONEKTA_PHONE,
        email: 'bliss@ironhack.com'//process.env.CONEKTA_EMAIL
      },
      line_items: [
        {
          name: course.name,
          unit_price: course.price,
          quantity: 1
        }
      ],      
      charges: [
        {
          payment_method: {
            type: "card",
            token_id: conektaTokenId
          }
        }
      ]
    },
    function(err, order) {
      if (err) return res.send(err);
      console.log(order.toObject());
      return res.send(order.toObject());
    }
  );
})


module.exports = router




